apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ads-deployment
  namespace: default
  labels:
    app.kubernetes.io/component: ms-ads
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ms-ads
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ms-ads
    spec:
      containers:
        - env:
            - name: MS_ADVERTISEMENT_URL
              valueFrom:
                secretKeyRef:
                  key: MS_ADVERTISEMENT_URL
                  name: ms.auth.secrets
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USERNAME
                  name: ms.auth.secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: ms.auth.secrets
            - name: MS_ADVERTISEMENT_PORT
              valueFrom:
                secretKeyRef:
                  key: MS_ADVERTISEMENT_PORT
                  name: ms.auth.secrets
            - name: CLINET_MS_USER_URL
              valueFrom:
                secretKeyRef:
                  key: CLINET_MS_USER_URL
                  name: ms.auth.secrets
            - name: CLIENT_MS_PERMISSION_URL
              valueFrom:
                secretKeyRef:
                  key: CLIENT_MS_PERMISSION_URL
                  name: ms.auth.secrets
          name: ms-ads
          image: yunuskazimov94/ms-ads
          ports:
            - name: http
              containerPort: 8042
              protocol: TCP