apiVersion: v1
kind: Service
metadata:
  name: ms-ads-loadbalancer
  labels:
    app.kubernetes.io/component: ms-ads
spec:
#  type: NodePort
  ports:
    - port: 80
      targetPort: 8042
  selector:
      app.kubernetes.io/component: ms-ads